/* Price Guessing Game — item database
 * Fields: e=emoji, n=name, d=condition/description, p=realistic market price (USD), c=category
 * Prices reflect typical secondhand / storage-auction market values for the stated condition.
 * The daily unit builder picks 1 item from each price quintile so every unit runs cheap → pricey.
 */

export const ITEMS = [
  // ---------- Electronics ----------
  { e: "🎧", n: "Sony WH-1000XM4 Wireless Headphones", d: "Used, excellent condition, no box, ear pads like new.", p: 138, c: "Electronics" },
  { e: "📱", n: "iPhone 12 64GB (Unlocked)", d: "Used, good condition, small scratch on corner, battery health 82%.", p: 210, c: "Electronics" },
  { e: "🎮", n: "Nintendo Switch OLED (White)", d: "Used, complete in box with dock and Joy-Cons.", p: 245, c: "Electronics" },
  { e: "💻", n: "MacBook Air M1 (2020, 8GB/256GB)", d: "Used, fair condition, minor scuffs on lid, cycles 340.", p: 420, c: "Electronics" },
  { e: "📺", n: "Samsung 55\" 4K Smart TV", d: "Open box, no stand, remote included, screen perfect.", p: 280, c: "Electronics" },
  { e: "🔋", n: "Anker 20,000mAh Power Bank", d: "New in box, sealed.", p: 39, c: "Electronics" },
  { e: "🔊", n: "Bose SoundLink Mini II Speaker", d: "Used, good condition, charges fine, small ding on grille.", p: 95, c: "Electronics" },
  { e: "🚁", n: "DJI Mini 2 Fly More Drone", d: "Used, one battery, propellers missing, case included.", p: 230, c: "Electronics" },
  { e: "📖", n: "Kindle Paperwhite (11th Gen)", d: "Used, good condition, no charger, screen flawless.", p: 65, c: "Electronics" },
  { e: "⌚", n: "Apple Watch Series 6 (44mm, GPS)", d: "Used, good condition, no charger, new sport band.", p: 145, c: "Electronics" },
  { e: "📻", n: "Vintage Sony Walkman WM-EX674", d: "Cassette player, fully working, belt clip included.", p: 85, c: "Electronics" },
  { e: "📷", n: "Canon EOS Rebel T6 DSLR + 18-55mm Lens", d: "Used, good condition, shutter count 12k, strap included.", p: 195, c: "Electronics" },
  { e: "🔉", n: "JBL Flip 5 Bluetooth Speaker", d: "Used, good condition, battery holds a full day.", p: 68, c: "Electronics" },
  { e: "🕹️", n: "PlayStation 4 Slim 1TB", d: "Used, one controller, HDMI cable, works perfectly.", p: 160, c: "Electronics" },
  { e: "🌊", n: "GoPro HERO9 Black", d: "Used, no case, two batteries, minor lens wear.", p: 120, c: "Electronics" },
  { e: "🛏️", n: "Google Nest Hub (2nd Gen)", d: "New in box, sealed.", p: 55, c: "Electronics" },
  { e: "🖱️", n: "Logitech MX Master 3S Mouse", d: "New in box, sealed.", p: 79, c: "Electronics" },
  { e: "🕹️", n: "Nintendo Game Boy Color (Teal)", d: "Used, working, battery cover missing, no box.", p: 95, c: "Electronics" },
  { e: "📲", n: "iPad 9th Gen (64GB, WiFi)", d: "Used, good condition, screen protector on since day one.", p: 180, c: "Electronics" },
  { e: "🎮", n: "Sony PS Vita (PCH-1000)", d: "Used, good condition, includes 2 game cards.", p: 110, c: "Electronics" },
  { e: "🏃", n: "Garmin Forerunner 245 GPS Watch", d: "Used, good condition, strap shows light wear.", p: 105, c: "Electronics" },
  { e: "🎵", n: "Sonos One SL Speaker", d: "Used, good condition, cable included.", p: 120, c: "Electronics" },
  { e: "🚪", n: "Ring Video Doorbell 3", d: "New in box, opened but never installed.", p: 99, c: "Electronics" },
  { e: "🥽", n: "Meta Quest 2 (128GB)", d: "Used, good condition, both controllers, elite strap.", p: 150, c: "Electronics" },
  { e: "🖨️", n: "Epson EcoTank ET-2760 Printer", d: "Used, works, ink tanks about half full.", p: 85, c: "Electronics" },
  { e: "🧭", n: "Garmin eTrex 22x Handheld GPS", d: "Used, good condition, no box.", p: 110, c: "Electronics" },
  { e: "🎤", n: "Blue Yeti USB Microphone", d: "Used, good condition, shock mount included.", p: 75, c: "Electronics" },

  // ---------- Collectibles ----------
  { e: "🃏", n: "Pokémon Card Lot (36 Loose Cards)", d: "Mostly commons and uncommons from the 2000s era.", p: 45, c: "Collectibles" },
  { e: "🐉", n: "Charizard — Base Set 4/102 (Heavily Played)", d: "1999 Wizards card, creased corner, no shadowless premium.", p: 450, c: "Collectibles" },
  { e: "📦", n: "Sealed Pokémon Base Set Booster Pack", d: "1999, unopened, warp visible, certifiable.", p: 900, c: "Collectibles" },
  { e: "⚾", n: "1986 Topps Roger Clemens Rookie Card", d: "Graded PSA 6, centering off left.", p: 25, c: "Collectibles" },
  { e: "🏀", n: "1997 Metal Universe Michael Jordan", d: "Ungraded, poor centering, sharp corners.", p: 150, c: "Collectibles" },
  { e: "🧸", n: "Ty Beanie Baby Princess Bear", d: "Tag attached, PVC version, mint-ish condition.", p: 35, c: "Collectibles" },
  { e: "⚾", n: "Signed Ken Griffey Jr. Baseball", d: "JSA certified autograph, display case included.", p: 180, c: "Collectibles" },
  { e: "🤖", n: "1979 Kenner Boba Fett Figure", d: "Loose, worn paint, weapon missing, no rocket-firing.", p: 260, c: "Collectibles" },
  { e: "🚀", n: "LEGO Millennium Falcon (75105)", d: "Built, complete, instructions included, no box.", p: 110, c: "Collectibles" },
  { e: "⚡", n: "LEGO Imperial Star Destroyer (75252)", d: "Sealed, box shelf-wear on corners.", p: 480, c: "Collectibles" },
  { e: "🏎️", n: "Hot Wheels 1995 Treasure Hunt Set (12 Cars)", d: "Loose but complete, cards show wear.", p: 90, c: "Collectibles" },
  { e: "🪙", n: "1921 Morgan Silver Dollar", d: "Circulated, Pittsburgh mint, ungraded.", p: 38, c: "Collectibles" },
  { e: "👧", n: "American Girl Doll Samantha (2000s)", d: "Used, good condition, original outfit, hair brushed.", p: 85, c: "Collectibles" },
  { e: "🍬", n: "Vintage Pez Dispenser Lot (15 Pieces)", d: "1970s–90s mix, no rare premiums, stems intact.", p: 60, c: "Collectibles" },
  { e: "🃏", n: "Yu-Gi-Oh! Blue-Eyes White Dragon (LOB)", d: "Played condition, edge whitening, tournament-legal.", p: 120, c: "Collectibles" },
  { e: "🏈", n: "1990 Donruss Bo Jackson Error Card", d: "The famous 'reverse negative' card, ungraded.", p: 15, c: "Collectibles" },
  { e: "🎵", n: "Michael Jackson — Thriller Vinyl (1982)", d: "Original pressing, VG+, sleeve has ring wear.", p: 28, c: "Collectibles" },
  { e: "🎮", n: "Nintendo NES Console Bundle", d: "Works, 2 controllers, Zapper, 3 common games.", p: 130, c: "Collectibles" },
  { e: "🎮", n: "Sega Genesis Model 1 Console", d: "Works, one controller, Sonic 1 included, no box.", p: 75, c: "Collectibles" },
  { e: "🥤", n: "Vintage Coca-Cola Machine (1950s)", d: "Vendo 81 style, restored cooling, coin mech works.", p: 2800, c: "Collectibles" },
  { e: "🧿", n: "Vintage Neon Bar Sign (Budweiser)", d: "Works, minor paint flaking on can graphic.", p: 320, c: "Collectibles" },
  { e: "🎰", n: "1970s Slot Machine (Working)", d: "Coin-operated, keys included, for entertainment only.", p: 450, c: "Collectibles" },
  { e: "💀", n: "Anatomical Skeleton Model (85cm)", d: "Classroom model, one hand loose, stand included.", p: 130, c: "Collectibles" },

  // ---------- Tools & Workshop ----------
  { e: "🔧", n: "DeWalt 20V Impact Driver Kit", d: "Used, one 2Ah battery, charger, hard case.", p: 105, c: "Tools" },
  { e: "🛠️", n: "Milwaukee M18 FUEL Hammer Drill Kit", d: "Used, two 5Ah batteries, case, brushless.", p: 165, c: "Tools" },
  { e: "🔩", n: "Snap-On 3/8\" Drive Ratchet", d: "Used, smooth action, owner's initials engraved.", p: 90, c: "Tools" },
  { e: "🧰", n: "Stanley 75-Piece Tool Set", d: "New in box, sealed plastic.", p: 35, c: "Tools" },
  { e: "🪚", n: "Bosch 12\" Sliding Miter Saw", d: "Used, good condition, one blade, no stand.", p: 190, c: "Tools" },
  { e: "⚡", n: "Honda EU2200i Portable Generator", d: "Used, runs great, 120 hours, no fuel can.", p: 480, c: "Tools" },
  { e: "🪚", n: "Vintage Craftsman Radial Arm Saw", d: "1950s cast-iron model, works, new blade.", p: 150, c: "Tools" },
  { e: "💨", n: "8-Gallon Air Compressor", d: "Used, holds pressure, loud but honest.", p: 95, c: "Tools" },
  { e: "🌀", n: "Dremel 4000 Rotary Tool Kit", d: "Used, complete with 30 attachments in case.", p: 55, c: "Tools" },
  { e: "🛡️", n: "Auto-Darkening Welding Helmet", d: "New in box, opened once.", p: 60, c: "Tools" },
  { e: "🪜", n: "Aluminum Extension Ladder (24ft)", d: "Used, good condition, rated 250lb.", p: 120, c: "Tools" },
  { e: "📦", n: "Industrial Pallet Jack", d: "Used, hydraulics work, one wheel chipped.", p: 220, c: "Tools" },

  // ---------- Home & Kitchen ----------
  { e: "🎂", n: "KitchenAid Artisan 5-Qt Stand Mixer", d: "Used, good condition, paddle + whisk + hook.", p: 175, c: "Home" },
  { e: "🍲", n: "Le Creuset 5.5qt Round Dutch Oven", d: "Used, flame orange, small chip on rim.", p: 140, c: "Home" },
  { e: "🌀", n: "Dyson V8 Cordless Vacuum", d: "Used, one battery, fair condition, filters new.", p: 135, c: "Home" },
  { e: "🍚", n: "Instant Pot Duo 6qt", d: "Used, good condition, inner pot lightly scratched.", p: 40, c: "Home" },
  { e: "🥤", n: "Vitamix 5200 Blender", d: "Used, good condition, container has clouding.", p: 185, c: "Home" },
  { e: "🥣", n: "Vintage Pyrex Mixing Bowl Set (4pc)", d: "1970s Spring Blossom pattern, one bowl has a flea bite.", p: 70, c: "Home" },
  { e: "🍽️", n: "Wedgwood China Service for 8", d: "Used, complete 40-piece set, no chips.", p: 220, c: "Home" },
  { e: "🔥", n: "Weber 22\" Kettle Grill", d: "Used, good condition, grate replaced last season.", p: 60, c: "Home" },
  { e: "🛌", n: "Tempur-Pedic Queen Mattress", d: "Used 8 years, always had a protector, no stains.", p: 150, c: "Home" },
  { e: "🧶", n: "Persian Hand-Knotted Rug (5×8ft)", d: "Wool, worn edges, needs a cleaning, no holes.", p: 450, c: "Home" },
  { e: "🪑", n: "Antique Oak Rocking Chair (c. 1900)", d: "Solid, original finish, one runner repaired.", p: 180, c: "Home" },
  { e: "☕", n: "Commercial Espresso Machine (Needs Repair)", d: "Two-group, powers on, no pressure — sold as-is.", p: 380, c: "Home" },
  { e: "🧻", n: "Bulk Paper Towels (12 Mega Rolls)", d: "Sealed warehouse overstock, name brand.", p: 25, c: "Home" },
  { e: "👗", n: "Wedding Dress (Worn Once)", d: "David's Bridal, size 6, professionally cleaned, boxed.", p: 180, c: "Home" },

  // ---------- Outdoors & Sports ----------
  { e: "🧊", n: "Yeti Tundra 45 Cooler", d: "Used, good condition, one latch replaced.", p: 165, c: "Outdoors" },
  { e: "⛺", n: "Coleman 6-Person Instant Tent", d: "Used once, all poles and stakes accounted for.", p: 85, c: "Outdoors" },
  { e: "🚲", n: "Trek 7200 Hybrid Bike", d: "Used, freshly tuned, new rear tire.", p: 190, c: "Outdoors" },
  { e: "⛳", n: "Ping Eye 2 Iron Set (3–PW)", d: "Used, steel shafts, new grips, grooves sharp.", p: 220, c: "Outdoors" },
  { e: "⚾", n: "Rawlings Heart of the Hide Glove", d: "Broken in, 11.75\", oil-treated leather.", p: 90, c: "Outdoors" },
  { e: "🏀", n: "Wilson NCAA Official Basketball", d: "New, inflated, never played outdoors.", p: 25, c: "Outdoors" },
  { e: "🚴", n: "Peloton Bike (Gen 2)", d: "Used, screen works, shoes and weights included.", p: 700, c: "Outdoors" },
  { e: "🏂", n: "Burton Snowboard + Bindings", d: "Used, base freshly waxed, small edge ding.", p: 210, c: "Outdoors" },
  { e: "🎣", n: "Ugly Stik Rod + Reel Combo", d: "Used, good condition, spooled with 10lb braid.", p: 45, c: "Outdoors" },
  { e: "🥤", n: "Yeti Rambler 30oz Tumbler", d: "Used, some scratches, lid intact.", p: 22, c: "Outdoors" },
  { e: "💧", n: "Hydro Flask 32oz Wide Mouth", d: "Used, dented at base, still insulates.", p: 20, c: "Outdoors" },
  { e: "🎣", n: "Tackle Box Full of Lures", d: "Mixed brands, 60+ lures, some vintage Rapalas.", p: 90, c: "Outdoors" },

  // ---------- Musical Instruments ----------
  { e: "🎸", n: "Fender Squier Stratocaster", d: "Used, gig bag included, new strings, minor belt rash.", p: 150, c: "Music" },
  { e: "🎸", n: "Yamaha FG800 Acoustic Guitar", d: "Used, good condition, solid spruce top, gig bag.", p: 120, c: "Music" },
  { e: "🎙️", n: "Shure SM58 Microphone", d: "Used, works perfectly, some finish wear.", p: 60, c: "Music" },
  { e: "🎹", n: "Casio 61-Key Portable Keyboard", d: "Used, good condition, stand included, no adapter.", p: 70, c: "Music" },
  { e: "🎺", n: "Vintage Conn Trumpet", d: "Plays well, case included, lacquer 70% intact.", p: 180, c: "Music" },
  { e: "🥁", n: "Roland TD-1DMK Electronic Drum Kit", d: "Used, good condition, throne and headphones included.", p: 330, c: "Music" },

  // ---------- Toys & Games ----------
  { e: "🧩", n: "Original Rubik's Cube (1980s)", d: "Used, stickers intact, turns a bit stiff.", p: 15, c: "Toys" },
  { e: "🎲", n: "Board Game Lot (12 Games)", d: "Mixed condition, all complete except one missing die.", p: 65, c: "Toys" },
  { e: "🏰", n: "Barbie Dreamhouse (2018)", d: "Used, complete, elevator works, no box.", p: 95, c: "Toys" },
  { e: "🚗", n: "Traxxas Slash 2WD RC Truck", d: "Used, one battery, body scuffed, runs strong.", p: 140, c: "Toys" },
  { e: "🔫", n: "Nerf Blaster Lot (8 Blasters)", d: "All working, 100+ darts, one missing stock.", p: 70, c: "Toys" },
  { e: "🤖", n: "G1 Transformers Optimus Prime (1984)", d: "Loose, missing fists and trailer, joints tight.", p: 280, c: "Toys" },
  { e: "🧸", n: "Squishmallow Lot (5 × 16\" Plush)", d: "Like new, tags attached, smoke-free unit.", p: 75, c: "Toys" },
  { e: "🛴", n: "Razor A5 Scooter", d: "Used, wheels smooth, folds correctly.", p: 35, c: "Toys" },
  { e: "🕹️", n: "Full-Size Arcade Cabinet (Multi-Game)", d: "60-in-1 replica, working coin door, monitor crisp.", p: 700, c: "Toys" },
  { e: "🦾", n: "Claw Machine (Working)", d: "Home size, works, includes 200 plush refills.", p: 550, c: "Toys" },

  // ---------- Fashion & Accessories ----------
  { e: "👜", n: "Louis Vuitton Keepall 55", d: "Used, good condition, patina on vachetta, dust bag.", p: 950, c: "Fashion" },
  { e: "⌚", n: "Rolex Oyster Perpetual (1990s)", d: "Runs well, no box or papers, needs a polish.", p: 2800, c: "Fashion" },
  { e: "🕶️", n: "Ray-Ban Aviator Sunglasses", d: "Used, original case, lenses have light scratches.", p: 55, c: "Fashion" },
  { e: "🧥", n: "The North Face Nuptse 700 Jacket", d: "Used, good condition, no rips, men's L.", p: 110, c: "Fashion" },
  { e: "👟", n: "Air Jordan 1 Mid (Worn)", d: "Used, 8/10 condition, original box, size 11.", p: 90, c: "Fashion" },
  { e: "🥾", n: "Red Wing Iron Ranger Boots", d: "Used, resoled once, leather well-conditioned.", p: 160, c: "Fashion" },
  { e: "💼", n: "Tumi Alpha 2 Carry-On", d: "Used, wheels smooth, initials on luggage tag.", p: 240, c: "Fashion" },

  // ---------- Miscellaneous Finds ----------
  { e: "📱", n: "Bin of Assorted Phone Cases (~120)", d: "Mixed models, mostly iPhone/Samsung, warehouse overstock.", p: 40, c: "Misc" },
  { e: "📚", n: "Box of 40 Hardcover Novels", d: "Bestsellers from the 2010s, all very good condition.", p: 55, c: "Misc" },
  { e: "🖼️", n: "Framed Thomas Kinkade Print", d: "Large, gallery-framed, glass intact.", p: 85, c: "Misc" },
  { e: "🪴", n: "Set of 6 Ceramic Planters", d: "Assorted sizes, one hairline crack.", p: 48, c: "Misc" },
  { e: "🚲", n: "Vintage Schwinn Sting-Ray (1970s)", d: "Original paint, needs tires, banana seat intact.", p: 350, c: "Misc" },
  { e: "🍖", n: "Commercial Meat Slicer", d: "Used, works, blade recently sharpened.", p: 210, c: "Misc" },
  { e: "🪟", n: "Antique Stained Glass Window Panel", d: "Circa 1910, one cracked pane, original lead.", p: 380, c: "Misc" },
  { e: "🎸", n: "Signed Fender Squier (Unsigned Mystery)", d: "Autograph unreadable, claimed to be famous.", p: 75, c: "Misc" },
  { e: "🛁", n: "Vintage Cast Iron Clawfoot Tub", d: "Refinished white, no fixtures included.", p: 550, c: "Misc" },
  { e: "🚗", n: "Vintage Gas Station Sign (Porcelain)", d: "1950s, 24\", excellent gloss, one small chip.", p: 620, c: "Misc" }
];
